### ISSUE TITLE
[FEATURE] Left-Justify Template Text by default

### ISSUE THREAD

**Issue by msprijatelj** [Tetragramm/lancer-field-guide-template#1]
Comparing between the official Lancer Core Book and this repo's initial PDF, the official Core Book uses Left Justified alignment for most body text (i.e. Helvetica-Font text outside of a table or system block), giving it a polished look. It would be helpful if such text in the .tex file was initially setup in the same way for easy copy-pasting.

**Comment by Tetragramm** [comment]
Sorry, looking in the pdf, which text is not left justified?
The tex file, of course, doesn't care about your alignment.  Whatever looks good to you. (Since it's plain text, the default is left justified.)  As for copy-paste, the entire second half is nearly a direct copy paste from the core book (barring the bold and keywords and such).

If that doesn't answer your question, perhaps you could show me what you mean?

**Comment by msprijatelj** [comment]
> 

What I mean is the official Lancer Core Book uses Left Justified Alignment by default (righthand side of paragraphs have even line endings):
![image](https://user-images.githubusercontent.com/44978587/188527869-54fa199a-6a5f-46e5-a282-94c98ec45911.png)

Whereas the PDF provided in this repo seems to use normal Left Alignment (righthand side of paragraphs have uneven line endings):
![image](https://user-images.githubusercontent.com/44978587/188527935-969409dc-c068-425f-97e9-9469941bd62e.png)

I admit I'm not super familiar with LaTeX, but if there's a way to automatically set text within the .tex file to use Left Justified Alignment like the official Core Book, it may be helpful for content creators.

**Comment by Tetragramm** [comment]
Ah, I do see.  I swapped that when I was getting all the box interiors to ragged right, and forgot to put it back.  
Should be fixed now.
